version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: subscription
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: mysql+pymysql://user:password@db/subscription
      JWT_SECRET_KEY: super-secret
    volumes:
      - .:/app

volumes:
  db_data:
