version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    working_dir: /app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      # Environment setup
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      FLASK_APP: main:app
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000

volumes:
  postgres_data:
