"""Increase password_hash length to 255

Revision ID: 05908cfc00bb
Revises: 351c63f08934
Create Date: 2025-07-22 17:07:53.326479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05908cfc00bb'
down_revision = '351c63f08934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
