"""Initial migration

Revision ID: 0e3cbb6759b2
Revises: 05908cfc00bb
Create Date: 2025-07-24 15:28:56.765748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3cbb6759b2'
down_revision = '05908cfc00bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.create_index('idx_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('idx_user_plan', ['user_id', 'plan_id'], unique=False)
        batch_op.create_index('idx_user_start_date', ['user_id', 'start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.drop_index('idx_user_start_date')
        batch_op.drop_index('idx_user_plan')
        batch_op.drop_index('idx_user_active')

    # ### end Alembic commands ###
