"""empty message

Revision ID: 5d1f3ec49003
Revises: 79bead3cb03b
Create Date: 2025-07-28 17:31:42.188920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1f3ec49003'
down_revision = '79bead3cb03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_active'))
        batch_op.drop_index(batch_op.f('idx_user_end_date'))
        batch_op.drop_index(batch_op.f('idx_user_plan'))
        batch_op.drop_index(batch_op.f('idx_user_start_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_start_date'), ['user_id', 'start_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_plan'), ['user_id', 'plan_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_end_date'), ['user_id', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_active'), ['user_id', 'is_active'], unique=False)

    # ### end Alembic commands ###
