"""empty message

Revision ID: 79bead3cb03b
Revises: 
Create Date: 2025-07-28 10:21:35.471510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bead3cb03b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.create_index('idx_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('idx_user_end_date', ['user_id', 'end_date'], unique=False)
        batch_op.create_index('idx_user_plan', ['user_id', 'plan_id'], unique=False)
        batch_op.create_index('idx_user_start_date', ['user_id', 'start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.drop_index('idx_user_start_date')
        batch_op.drop_index('idx_user_plan')
        batch_op.drop_index('idx_user_end_date')
        batch_op.drop_index('idx_user_active')

    op.drop_table('user_subscription')
    op.drop_table('user')
    op.drop_table('plan')
    # ### end Alembic commands ###
